# name: pavage-asphalte-laval-montreal.ca  Continuous Integration

# on:
#   push:
#     branches:
#       - master

# jobs:
#   pavagelaval_Automated_Deployment_Process:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Retrieve actions/checkout@v2 💻
#       uses: actions/checkout@v2
#       with:
#         ref: ${{ github.ref }}

#     - name: Syncing development with prod environment Pavage Laval
#       uses: appleboy/ssh-action@master
#       with:
#         host: ${{ secrets.SERVER_HOSTNAME }}
#         username: ${{ secrets.SERVER_USERNAME }}
#         password: ${{ secrets.SERVER_PASSWORD }}
#         port: ${{ secrets.SERVER_PORT }}
#         script: |
#           cd pavage_laval
#           rm package-lock.json
#           rm -r node_modules
#           rm -r ./miscellaneous/db/dump.txt
#           chmod -R 755 models
#           rm -rf ./models/*
#           git pull https://${{ secrets.GITHUUB_USERNAME }}:${{ secrets.GITHUUB_PASSWORD }}@github.com/${{ secrets.GITHUUB_USERNAME }}/pavage_laval.git master
#           npm install
#           mysql -u ${{ secrets.DB_USERNAME }} -p${{ secrets.DB_USERPASSWORD }} ${{ secrets.DB_NAME }} < ./miscellaneous/db/dump.txt
#           sequelize-auto -o \"./models\" -d ${{ secrets.DB_NAME }} -h ${{ secrets.DB_HOST }} -u ${{ secrets.DB_USERNAME }} -p ${{ secrets.DB_PORT }} -x ${{ secrets.DB_USERPASSWORD }} -e mysql
#           pm2 restart pavage_laval